// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://missing-env-var.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "missing-env-var-key";

if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.error("🚨 CRITICAL ERROR: Supabase Environment Variables are missing! You must add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY locally in your Vercel Project Settings.");
  if (typeof window !== "undefined") {
    setTimeout(() => {
      document.body.innerHTML = `
        <div style="padding: 40px; text-align: center; font-family: sans-serif; background: #111; color: white; height: 100vh; display: flex; flex-direction: column; justify-content: center;">
          <h1 style="color: #ff4444; margin-bottom: 20px;">Vercel Environment Variables Missing</h1>
          <p style="font-size: 18px; line-height: 1.6;">Your site is trying to load, but it cannot connect to the database.</p>
          <p style="font-size: 18px; line-height: 1.6;">To fix this white screen, go to your <b>Vercel Dashboard &gt; Settings &gt; Environment Variables</b> and add:</p>
          <ul style="list-style: none; padding: 20px; background: #222; border-radius: 8px; display: inline-block; text-align: left; margin: 20px auto;">
            <li><code style="color: #72f1b8;">VITE_SUPABASE_URL</code></li>
            <li><code style="color: #72f1b8;">VITE_SUPABASE_PUBLISHABLE_KEY</code></li>
            <li><code style="color: #72f1b8;">VITE_SUPABASE_PROJECT_ID</code> (optional but recommended)</li>
          </ul>
          <p style="font-size: 16px; color: #aaa;">You can find these values in your local <code style="color: white; background: #333; padding: 2px 6px; border-radius: 4px;">.env</code> file.</p>
          <p style="font-size: 16px; color: #ffeb3b; margin-top: 20px;">After adding them, you must <b>Redeploy</b> in Vercel for changes to take effect.</p>
        </div>
      `;
    }, 100); // Overlay the root div shortly after load
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.sessionStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});