// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://missing-env-var.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "missing-env-var-key";

if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.error("🚨 CRITICAL ERROR: Supabase Environment Variables are missing! You must add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY locally in your Vercel Project Settings.");
  if (typeof window !== "undefined") {
    setTimeout(() => {
      const el = document.createElement('div');
      el.style.cssText = 'padding:40px;text-align:center;font-family:sans-serif;background:#111;color:white;height:100vh;display:flex;flex-direction:column;justify-content:center;';
      
      const h1 = document.createElement('h1');
      h1.style.cssText = 'color:#ff4444;margin-bottom:20px;';
      h1.textContent = 'Vercel Environment Variables Missing';
      
      const p1 = document.createElement('p');
      p1.style.cssText = 'font-size:18px;line-height:1.6;';
      p1.textContent = 'Your site is trying to load, but it cannot connect to the database.';
      
      const p2 = document.createElement('p');
      p2.style.cssText = 'font-size:18px;line-height:1.6;';
      p2.textContent = 'To fix this, go to Vercel Dashboard > Settings > Environment Variables and add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.';
      
      const p3 = document.createElement('p');
      p3.style.cssText = 'font-size:16px;color:#ffeb3b;margin-top:20px;';
      p3.textContent = 'After adding them, you must Redeploy in Vercel for changes to take effect.';
      
      el.appendChild(h1);
      el.appendChild(p1);
      el.appendChild(p2);
      el.appendChild(p3);
      
      document.body.replaceChildren(el);
    }, 100);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});